# Generated by Django 4.0.4 on 2022-07-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=255)),
                ('job_role', models.CharField(choices=[('VN', 'Voodoo newstarter'), ('SSSE', 'Semi-skilled SE'), ('SSE', 'Skilled SE'), ('VTS', 'Voodoo Temple Supervisor')], max_length=60)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('cv_upload', models.FileField(max_length=254, upload_to=None)),
            ],
        ),
    ]
