# Generated by Django 4.0.4 on 2022-07-26 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_application_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacantJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(choices=[('VN', 'Voodoo newstarter'), ('SSSE', 'Semi-skilled SE'), ('SSE', 'Skilled SE'), ('VTS', 'Voodoo Temple Supervisor')], max_length=40)),
                ('vacant', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='job_role',
            field=models.ForeignKey(choices=[('VN', 'Voodoo newstarter'), ('SSSE', 'Semi-skilled SE'), ('SSE', 'Skilled SE'), ('VTS', 'Voodoo Temple Supervisor')], max_length=60, on_delete=django.db.models.deletion.CASCADE, related_name='job_role', to='backend.vacantjob'),
        ),
    ]
